variables:
  UTEST_TEST_DIR: tests
  UTEST_TEST_CMD: "make run"
  UTEST_TEST_COV_CMD: "make coverage"
  DOC_GEN_CMD: "make doc"
  BUILD_TARGET: libamxc
  PC_BUILD_COMP_YOCTO: "off"

include:
  # include default templates (needed by the default pipelines)
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/master/ambiorix-default-pipeline.yml'

